name: Deploy in production

on:
  push:
    branches:
      - main

jobs:
  publish-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: "worker"
          docker_build_args: TG_BOT_TOKEN
        env:
          TG_BOT_TOKEN: ${{secrets.TELEGRAM_BOT_TOKEN}}
