name: Push docker image to the registry

on:
  push:
    branches:
       - main

jobs:
  publish-docker-image:
   runs-on: ubuntu-latest
   steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        run: |
             docker build . --tag ghcr.io/imgios/nonnatittina-bot:latest
             docker push ghcr.io/imgios/nonnatittina-bot:latest